version: '3'

services:

  beckend:
    # build: 
    #   context: ./Api
    image: "observableapi"
    ports:
      - 9090:80

  frontend:
    build: 
      context: ./WebApp
      args:
        api_url: localhost:9090
    ports:
      - 9096:80

# docker-compose rm --all
# docker-compose build --no-cache
# docker-compose up -d --force-recreate      


